name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build project
        env: 
          NODE_ENV: production
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        run: npm run build  # Adjust this command if your build script is different
 
      - name: Log to Console
        run: |
          echo "This is a log message."
          echo "Another log message for debugging purposes."
          echo "FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}"
          echo "TEST_KEY: ${{ secrets.TEST_KEY }}"

      - name: Log to Console2.0
        run: |
          if [ -z "${{ secrets.FIREBASE_API_KEY }}" ]; then echo "FIREBASE_API_KEY is not set"; else echo "FIREBASE_API_KEY is set"; fi
          if [ -z "${{ secrets.TEST_KEY }}" ]; then echo "TEST_KEY is not set"; else echo "TEST_KEY is set"; fi


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./login-signup-form  # Adjust this to your build output directory
          publish_branch: gh-pages  # Ensure the branch is set to gh-pages